Update MeroQuickStart.md
Fix following error - 
error: pathspec 'commit’' did not match any file(s) known to git.

resolution :
On command line if args is made of spaces then double quotes are required while giving inline commit message